/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Finestra.Utente;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.*;
import javax.swing.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.ArrayList;
import java.util.List;
import java.time.LocalTime;
import javax.swing.ImageIcon;
/**
 *
 * @author p_leonardo_c
 */


public class CompraBiglietto extends javax.swing.JPanel {

    /**
     * Creates new form CompraBiglietto
     */
    private Integer totBigliettoNormale=0;
    private Integer totBigliettoRidotto=0;
    private List<LocalTime> orarioSrck = new ArrayList<>();






    private List<JButton> orarioBoton;
    private int indiceOrario=-1;
    private JButton BotonSelezionato = null;
    private float prezzoNormale = 0.0f;

    private float prezzoRidotto = 0.0f;

    // Supponiamo che tu abbia questa lista da qualche parte nella tua classe
    private List<String> percorsiImmagini = new ArrayList<>();

    // Metodo per aggiornare l'immagine
    private void aggiornaFilmImmagine() {
        SwingUtilities.invokeLater(() -> {
            if (jPanel1.getWidth() > 0 && jPanel1.getHeight() > 0) {
                int i = 0; // Supponiamo che tu voglia caricare l'immagine 0.png
                String percorsoImmagine = "src/main/java/Immagini/" + i + ".png";
                ImageIcon icona = new ImageIcon(percorsoImmagine);
                System.out.println("Percorso immagine: " + percorsoImmagine);
                System.out.println("Dimensioni jPanel1: " + jPanel1.getWidth() + "x" + jPanel1.getHeight());

                Image immagineRidimensionata = icona.getImage().getScaledInstance(jPanel1.getWidth(), jPanel1.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon iconaRidimensionata = new ImageIcon(immagineRidimensionata);

                FilmImmagine.setIcon(iconaRidimensionata);

                jPanel1.revalidate();
                jPanel1.repaint();
            } else {
                System.out.println("Dimensioni jPanel1 non valide al momento dell'aggiornamento dell'immagine.");
            }
        });
    }






    public void CambiaPrezzo(){
        
        PrezzoAquisto.setText(""+(prezzoNormale+prezzoRidotto));
        
    }


    public CompraBiglietto() {
        orarioBoton = new ArrayList<>();
        initComponents();

        orarioSrck.add(LocalTime.of(14,15));
        orarioSrck.add(LocalTime.of(18,15));

        for(int i=0; i<orarioSrck.size();i++) {
            AggiungOrarioFilmBottone(orarioSrck.get(i));
        }

        jPanel1.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                super.componentResized(e);
                aggiornaFilmImmagine(); // Questo metodo verrà chiamato dopo ogni ridimensionamento
            }
        });




    }

    private void AggiungOrarioFilmBottone(LocalTime Ora){
            JButton boton = new JButton("Ore: "+Ora);
         // Aggiungi il bottone alla lista
        orarioBoton.add(boton);
        OrarioFilm.add(boton);

            final int indice = orarioBoton.size() - 1; // Indice del bottone appena aggiunto
            boton.addActionListener(e -> {
                if (indiceOrario != -1) {
                    // Resetta il bordo del bottone precedentemente selezionato
                    orarioBoton.get(indiceOrario).setBorder(null);
                    // Opzionale: riabilita il bottone precedentemente selezionato
                    orarioBoton.get(indiceOrario).setEnabled(true);
                }
                // Imposta il bordo del bottone attualmente selezionato a rosso
                boton.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
                indiceOrario = indice;

                // Disabilita tutti i bottoni tranne quello selezionato
                for (int i = 0; i < orarioBoton.size(); i++) {
                    if (i != indiceOrario) {
                        orarioBoton.get(i).setEnabled(false);
                    }
                }
            });

            // Altri settaggi del bottone...

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prePagamentoPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        FilmImmagine = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PrezzoAquisto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        MainPanelBiglietti = new javax.swing.JPanel();
        PanelBiglietto = new javax.swing.JPanel();
        piuBigliettoNormale = new javax.swing.JButton();
        menoBigliettoNormale = new javax.swing.JButton();
        StaticoNbiglietto = new javax.swing.JLabel();
        contatoreBigliettoNormale = new javax.swing.JLabel();
        piuBigliettoRidotto = new javax.swing.JButton();
        contatoreBigliettoRidotto = new javax.swing.JLabel();
        menoBigliettoRidotto = new javax.swing.JButton();
        StaticoNbigliettoRidotto = new javax.swing.JLabel();
        OrarioFilm = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        prePagamentoPanel.setBackground(new java.awt.Color(204, 255, 204));
        prePagamentoPanel.setLayout(new java.awt.GridLayout(3, 1));

        jLabel2.setFont(new java.awt.Font("Noto Sans CJK SC Medium", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FILM");
        prePagamentoPanel.add(jLabel2);

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(FilmImmagine, java.awt.BorderLayout.CENTER);

        prePagamentoPanel.add(jPanel1);

        jLabel5.setBackground(new java.awt.Color(0, 153, 0));
        jLabel5.setFont(new java.awt.Font("Fira Sans ExtraBold", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Prezzo totale:");
        prePagamentoPanel.add(jLabel5);

        PrezzoAquisto.setBackground(new java.awt.Color(0, 153, 0));
        PrezzoAquisto.setFont(new java.awt.Font("Fira Sans ExtraBold", 1, 24)); // NOI18N
        PrezzoAquisto.setForeground(new java.awt.Color(0, 153, 0));
        PrezzoAquisto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PrezzoAquisto.setText("0");
        prePagamentoPanel.add(PrezzoAquisto);

        jLabel3.setFont(new java.awt.Font("Fira Sans Medium", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SALA: ");
        jLabel3.setToolTipText("");
        prePagamentoPanel.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Fira Sans Medium", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("3");
        jLabel4.setToolTipText("");
        prePagamentoPanel.add(jLabel4);

        add(prePagamentoPanel, java.awt.BorderLayout.LINE_END);

        MainPanelBiglietti.setBackground(new java.awt.Color(102, 0, 0));
        MainPanelBiglietti.setLayout(new java.awt.BorderLayout());

        PanelBiglietto.setBackground(new java.awt.Color(255, 255, 255));

        piuBigliettoNormale.setText("+");
        piuBigliettoNormale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piuBigliettoNormaleActionPerformed(evt);
            }
        });

        menoBigliettoNormale.setText("-");
        menoBigliettoNormale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menoBigliettoNormaleActionPerformed(evt);
            }
        });

        StaticoNbiglietto.setText("N. biglietto");

        contatoreBigliettoNormale.setText("0");

        piuBigliettoRidotto.setText("+");
        piuBigliettoRidotto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piuBigliettoRidottoActionPerformed(evt);
            }
        });

        contatoreBigliettoRidotto.setText("0");

        menoBigliettoRidotto.setText("-");
        menoBigliettoRidotto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menoBigliettoRidottoActionPerformed(evt);
            }
        });

        StaticoNbigliettoRidotto.setText("N. biglietti ridotti");

        javax.swing.GroupLayout PanelBigliettoLayout = new javax.swing.GroupLayout(PanelBiglietto);
        PanelBiglietto.setLayout(PanelBigliettoLayout);
        PanelBigliettoLayout.setHorizontalGroup(
            PanelBigliettoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBigliettoLayout.createSequentialGroup()
                .addGroup(PanelBigliettoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBigliettoLayout.createSequentialGroup()
                        .addGroup(PanelBigliettoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelBigliettoLayout.createSequentialGroup()
                                .addComponent(menoBigliettoRidotto, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(contatoreBigliettoRidotto))
                            .addGroup(PanelBigliettoLayout.createSequentialGroup()
                                .addComponent(menoBigliettoNormale, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(contatoreBigliettoNormale)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelBigliettoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(piuBigliettoNormale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(piuBigliettoRidotto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelBigliettoLayout.createSequentialGroup()
                        .addGroup(PanelBigliettoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StaticoNbiglietto)
                            .addComponent(StaticoNbigliettoRidotto))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelBigliettoLayout.setVerticalGroup(
            PanelBigliettoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBigliettoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StaticoNbiglietto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelBigliettoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(piuBigliettoNormale, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menoBigliettoNormale, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contatoreBigliettoNormale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(StaticoNbigliettoRidotto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelBigliettoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(piuBigliettoRidotto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menoBigliettoRidotto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contatoreBigliettoRidotto))
                .addGap(33, 33, 33))
        );

        MainPanelBiglietti.add(PanelBiglietto, java.awt.BorderLayout.PAGE_START);

        OrarioFilm.setLayout(new java.awt.GridLayout(1, 0));
        MainPanelBiglietti.add(OrarioFilm, java.awt.BorderLayout.CENTER);

        add(MainPanelBiglietti, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void piuBigliettoNormaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piuBigliettoNormaleActionPerformed
        // TODO add your handling code here:

                totBigliettoNormale++;
                prezzoNormale += 2.5;

                contatoreBigliettoNormale.setText(""+totBigliettoNormale);
                
                CambiaPrezzo();

    }//GEN-LAST:event_piuBigliettoNormaleActionPerformed

    private void menoBigliettoNormaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menoBigliettoNormaleActionPerformed
        // TODO add your handling code here:
        if(totBigliettoNormale > 0){
            totBigliettoNormale--;
        prezzoNormale -= 2.5;
        contatoreBigliettoNormale.setText(""+totBigliettoNormale);
        CambiaPrezzo();
        }
        
    }//GEN-LAST:event_menoBigliettoNormaleActionPerformed

    private void piuBigliettoRidottoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piuBigliettoRidottoActionPerformed
        // TODO add your handling code here:
        totBigliettoRidotto++;
        prezzoRidotto += 1.5;
        contatoreBigliettoRidotto.setText(""+totBigliettoRidotto);
        CambiaPrezzo();

    }//GEN-LAST:event_piuBigliettoRidottoActionPerformed

    private void menoBigliettoRidottoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menoBigliettoRidottoActionPerformed
        // TODO add your handling code here:
        if(totBigliettoRidotto > 0){
            totBigliettoRidotto--;
            prezzoRidotto -= 1.5;
            contatoreBigliettoRidotto.setText(""+totBigliettoRidotto);
            CambiaPrezzo();
        }

    }//GEN-LAST:event_menoBigliettoRidottoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FilmImmagine;
    private javax.swing.JPanel MainPanelBiglietti;
    private javax.swing.JPanel OrarioFilm;
    private javax.swing.JPanel PanelBiglietto;
    private javax.swing.JLabel PrezzoAquisto;
    private javax.swing.JLabel StaticoNbiglietto;
    private javax.swing.JLabel StaticoNbigliettoRidotto;
    private javax.swing.JLabel contatoreBigliettoNormale;
    private javax.swing.JLabel contatoreBigliettoRidotto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton menoBigliettoNormale;
    private javax.swing.JButton menoBigliettoRidotto;
    private javax.swing.JButton piuBigliettoNormale;
    private javax.swing.JButton piuBigliettoRidotto;
    private javax.swing.JPanel prePagamentoPanel;
    // End of variables declaration//GEN-END:variables
}
