/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Finestra.Utente;

import Finestra.Utente.Biglietti;
import Finestra.Utente.Pagina1;

/**
 *
 * @author p_leonardo_c
 */
public class FinestraUtente extends javax.swing.JFrame {

    /**
     * Creates new form FinestraUtente
     */
    public FinestraUtente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Menu = new javax.swing.JPanel();
        BBiglietti = new javax.swing.JButton();
        BFILM = new javax.swing.JButton();
        Content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 720));
        setResizable(false);

        Menu.setBackground(new java.awt.Color(51, 51, 51));
        Menu.setLayout(new java.awt.GridBagLayout());

        BBiglietti.setText(" Biglietti");
        BBiglietti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBigliettiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 49;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 6, 214, 6);
        Menu.add(BBiglietti, gridBagConstraints);

        BFILM.setText("   FILM  ");
        BFILM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFILMActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 49;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 6, 0, 6);
        Menu.add(BFILM, gridBagConstraints);

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        Content.setBackground(new java.awt.Color(102, 0, 0));
        Content.setLayout(new java.awt.BorderLayout());
        getContentPane().add(Content, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BBigliettiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBigliettiActionPerformed
        // TODO add your handling code here:
            Biglietti b1 = new Biglietti();
        
        Content.removeAll();
        Content.add(b1);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_BBigliettiActionPerformed

    private void BFILMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFILMActionPerformed
        // TODO add your handling code here
        Pagina1 p1 = new Pagina1();
        
        Content.removeAll();
        Content.add(p1);
        Content.revalidate();
        Content.repaint();
        //458 223
    }//GEN-LAST:event_BFILMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinestraUtente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinestraUtente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinestraUtente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinestraUtente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinestraUtente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBiglietti;
    private javax.swing.JButton BFILM;
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Menu;
    // End of variables declaration//GEN-END:variables
}
