/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Finestra.Utente;

import Finestra.Utente.CompraBiglietto;
import Finestra.Utente.Acquisto;
import javax.swing.*;

/**
 *
 * @author p_leonardo_c
 */
public class Pagina1 extends javax.swing.JPanel {

    /**
     * Creates new form Pagina1
     */

    private SceltaSpettacolo Films;
    private int Bavanti = 1;
    private int Bannulla = 1;
    public Pagina1() {
        initComponents();
        Films = new SceltaSpettacolo();
        ContentPAG.removeAll();
        ContentPAG.add(Films);
        ContentPAG.revalidate();
        ContentPAG.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContentPAG = new javax.swing.JPanel();
        MenuPanelFilm = new javax.swing.JPanel();
        BAnulla = new javax.swing.JButton();
        BContinua1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(621, 433));
        setLayout(new java.awt.BorderLayout());

        ContentPAG.setBackground(new java.awt.Color(0, 51, 51));
        ContentPAG.setLayout(new java.awt.BorderLayout());
        add(ContentPAG, java.awt.BorderLayout.CENTER);

        MenuPanelFilm.setBackground(new java.awt.Color(102, 0, 0));

        BAnulla.setText("Annulla");
        BAnulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAnullaActionPerformed(evt);
            }
        });

        BContinua1.setText("Continua ->");
        BContinua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BContinua1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelFilmLayout = new javax.swing.GroupLayout(MenuPanelFilm);
        MenuPanelFilm.setLayout(MenuPanelFilmLayout);
        MenuPanelFilmLayout.setHorizontalGroup(
            MenuPanelFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelFilmLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(BAnulla, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addComponent(BContinua1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        MenuPanelFilmLayout.setVerticalGroup(
            MenuPanelFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelFilmLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(MenuPanelFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BAnulla, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BContinua1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        add(MenuPanelFilm, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void BAnullaActionPerformed(java.awt.event.ActionEvent evt) {
        switch (Bannulla){
            case 1:
                Films.annullaSelezione();
                break;
            case 2:
                Bavanti--;
                Films.annullaSelezione();
                ContentPAG.removeAll();
                ContentPAG.add(Films);
                ContentPAG.revalidate();
                ContentPAG.repaint();



        }
    }

    private void BContinua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BContinua1ActionPerformed
        // TODO add your handling code here:

        switch (Bavanti){
            case 1:
                if(Films.getIndiceSelezionato() != -1) {
                    Bavanti++;
                    Bannulla++;
                    ContentPAG.removeAll();
                    CompraBiglietto b1 = new CompraBiglietto();
                    ContentPAG.add(b1);
                    ContentPAG.revalidate();
                    ContentPAG.repaint();

                    BContinua1.setText("Aquista");

                }
                else{
                    JOptionPane.showMessageDialog(null,"devi selezionare prima un film");

                }
                break;
            case 2:
                Bannulla++;
                ContentPAG.removeAll();
                Acquisto aq1 = new Acquisto();
                ContentPAG.add(aq1);
                ContentPAG.revalidate();
                ContentPAG.repaint();

        }

    }//GEN-LAST:event_BContinua1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAnulla;
    private javax.swing.JButton BContinua1;
    private javax.swing.JPanel ContentPAG;
    private javax.swing.JPanel MenuPanelFilm;
    // End of variables declaration//GEN-END:variables
}
