/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Finestra.Amministratore;

import Cinema.domain.Amministratore;
import Cinema.domain.Ruolo;
import Finestra.Login.Login;
/**
 *
 * @author p_leonardo_c
 */
public class GUIadmin extends javax.swing.JFrame {

    /**
     * Creates new form GUIadmin
     */

    private Amministratore a1 = null;

    public GUIadmin(Amministratore a1) {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        GestoreFilmTitolo = new javax.swing.JLabel();
        comboEliminaFilm = new javax.swing.JComboBox<>();
        ScrollTabella = new javax.swing.JScrollPane();
        tabellaSpettacoli = new javax.swing.JTable();
        TitoloSpettacoli = new javax.swing.JLabel();
        TitoloFilmInserisci = new javax.swing.JLabel();
        FilmInserisci = new javax.swing.JTextField();
        Titolodurata = new javax.swing.JLabel();
        TitoloGestoreSale = new javax.swing.JLabel();
        TitoloNuovaSala = new javax.swing.JLabel();
        InserisciNuovaSala = new javax.swing.JTextField();
        PostiInserisci = new javax.swing.JSpinner();
        TitoloPostiInserisci = new javax.swing.JLabel();
        AggiungiSalaButton = new javax.swing.JButton();
        TitoloSelezionaSala = new javax.swing.JLabel();
        SelezionaSala = new javax.swing.JComboBox<>();
        TitoloSelezionaOrario = new javax.swing.JLabel();
        IserisciOrario = new javax.swing.JTextField();
        TitoloModificaEliminaSala = new javax.swing.JLabel();
        SelezionaSalaElimina = new javax.swing.JComboBox<>();
        TitoloNomeSala = new javax.swing.JLabel();
        InserisciNomeSala = new javax.swing.JTextField();
        titoloPostiModifica = new javax.swing.JLabel();
        ButtonModificaSala = new javax.swing.JButton();
        ButtonEliminaSala = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        EliminaSpettacolo = new javax.swing.JButton();
        AggiungiFilmButton = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        TitoloEliminaFIlm = new javax.swing.JLabel();
        EliminaButtonFilm = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        TitoloCreaSpettacolo = new javax.swing.JLabel();
        SelezionaFilmAggiungi = new javax.swing.JComboBox<>();
        FilmTitoloAggiungi = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        TitoloSalaModifica = new javax.swing.JLabel();
        SalaModifica = new javax.swing.JComboBox<>();
        TitoloFilm = new javax.swing.JLabel();
        FilmModifica = new javax.swing.JComboBox<>();
        ModificaOrario = new javax.swing.JTextField();
        OrarioModificaTitolo = new javax.swing.JLabel();
        AggiungiButtonFilm = new javax.swing.JButton();
        ModificaSpettacoloButton = new javax.swing.JButton();
        DurataOreFilmAggiungi = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1580, 868));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GestoreFilmTitolo.setFont(new java.awt.Font("Fira Sans", 1, 18)); // NOI18N
        GestoreFilmTitolo.setForeground(new java.awt.Color(153, 153, 0));
        GestoreFilmTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GestoreFilmTitolo.setText("GESTORE DEGLI Film");

        comboEliminaFilm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboEliminaFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEliminaFilmActionPerformed(evt);
            }
        });

        tabellaSpettacoli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Film", "Sala", "orario", "Copertina"
            }
        ));
        ScrollTabella.setViewportView(tabellaSpettacoli);

        TitoloSpettacoli.setText("Spettacoli creati");

        TitoloFilmInserisci.setText("Titolo");

        Titolodurata.setText("Durata");

        TitoloGestoreSale.setText("GESTORE DELLE SALE");

        TitoloNuovaSala.setText("NOME SALA");

        InserisciNuovaSala.setText("jTextField3");

        TitoloPostiInserisci.setText("Posti sala");

        AggiungiSalaButton.setText("AGGIUNGI SALA");
        AggiungiSalaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AggiungiSalaButtonActionPerformed(evt);
            }
        });

        TitoloSelezionaSala.setText("Sala");

        SelezionaSala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        TitoloSelezionaOrario.setText("Orario");

        IserisciOrario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IserisciOrarioActionPerformed(evt);
            }
        });

        TitoloModificaEliminaSala.setText("MODIFICA/ELIMINA SALA");

        SelezionaSalaElimina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        TitoloNomeSala.setText("Nome sala");

        InserisciNomeSala.setText("jTextField5");

        titoloPostiModifica.setText("Posti");

        ButtonModificaSala.setText("Modifica");

        ButtonEliminaSala.setText("ELIMINA");
        ButtonEliminaSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminaSalaActionPerformed(evt);
            }
        });

        EliminaSpettacolo.setText("Elimina");

        AggiungiFilmButton.setText("Aggiungi");
        AggiungiFilmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AggiungiFilmButtonActionPerformed(evt);
            }
        });

        TitoloEliminaFIlm.setText("Elimina Film");

        EliminaButtonFilm.setText("Elimina");

        TitoloCreaSpettacolo.setText("CreaSpettacolo");

        SelezionaFilmAggiungi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        FilmTitoloAggiungi.setText("Film");

        TitoloSalaModifica.setText("Sala");

        SalaModifica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        TitoloFilm.setText("Film");

        FilmModifica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ModificaOrario.setText("jTextField4");
        ModificaOrario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaOrarioActionPerformed(evt);
            }
        });

        OrarioModificaTitolo.setText("orario");

        AggiungiButtonFilm.setText("aggiungi");

        ModificaSpettacoloButton.setText("Modifica");

        DurataOreFilmAggiungi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 ora", "2 ore", "3 ore", "4 ore", "5 ore", "6 ore" }));
        DurataOreFilmAggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DurataOreFilmAggiungiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator6)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TitoloEliminaFIlm)
                                .addComponent(ScrollTabella, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(FilmTitoloAggiungi)
                                .addComponent(SelezionaFilmAggiungi, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(comboEliminaFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(EliminaButtonFilm))
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TitoloFilmInserisci)
                                            .addComponent(FilmInserisci, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(DurataOreFilmAggiungi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(AggiungiFilmButton))
                                            .addComponent(Titolodurata))))))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(TitoloSpettacoli))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(163, 163, 163)
                            .addComponent(AggiungiButtonFilm)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FilmModifica, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TitoloFilm)
                                    .addComponent(TitoloSalaModifica)
                                    .addComponent(SalaModifica, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EliminaSpettacolo, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(81, 81, 81)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ModificaSpettacoloButton)
                                    .addComponent(ModificaOrario, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(OrarioModificaTitolo)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(GestoreFilmTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TitoloCreaSpettacolo)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(TitoloSelezionaSala)
                                            .addGap(196, 196, 196)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(TitoloSelezionaOrario)
                                                .addComponent(IserisciOrario, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(SelezionaSala, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(76, 76, 76)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TitoloModificaEliminaSala)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(SelezionaSalaElimina, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ButtonEliminaSala, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(ButtonModificaSala, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(TitoloNomeSala)
                                                .addComponent(titoloPostiModifica))
                                            .addGap(31, 31, 31)
                                            .addComponent(InserisciNomeSala, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                    .addComponent(TitoloPostiInserisci)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(PostiInserisci))
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addComponent(TitoloNuovaSala)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(InserisciNuovaSala, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(AggiungiSalaButton))
                                        .addComponent(TitoloGestoreSale, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator2)))))))
                .addContainerGap(1214, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GestoreFilmTitolo)
                    .addComponent(TitoloGestoreSale))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitoloFilmInserisci)
                    .addComponent(Titolodurata))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FilmInserisci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AggiungiFilmButton)
                            .addComponent(DurataOreFilmAggiungi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TitoloEliminaFIlm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboEliminaFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EliminaButtonFilm)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TitoloNuovaSala)
                            .addComponent(InserisciNuovaSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TitoloPostiInserisci)
                            .addComponent(PostiInserisci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(AggiungiSalaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(TitoloCreaSpettacolo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TitoloSelezionaSala)
                                    .addComponent(TitoloSelezionaOrario))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SelezionaSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IserisciOrario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FilmTitoloAggiungi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SelezionaFilmAggiungi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(AggiungiButtonFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(TitoloModificaEliminaSala)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SelezionaSalaElimina, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonModificaSala, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonEliminaSala, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TitoloNomeSala)
                                    .addComponent(InserisciNomeSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(titoloPostiModifica))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183)))
                .addGap(6, 6, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(TitoloSpettacoli)
                .addGap(18, 18, 18)
                .addComponent(ScrollTabella, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitoloSalaModifica)
                    .addComponent(OrarioModificaTitolo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalaModifica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModificaOrario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TitoloFilm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FilmModifica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EliminaSpettacolo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModificaSpettacoloButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModificaOrarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaOrarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificaOrarioActionPerformed

    private void ButtonEliminaSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminaSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonEliminaSalaActionPerformed

    private void IserisciOrarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IserisciOrarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IserisciOrarioActionPerformed

    private void AggiungiSalaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AggiungiSalaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AggiungiSalaButtonActionPerformed

    private void AggiungiFilmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AggiungiFilmButtonActionPerformed

        String Titolo;
        int Ora;
        
        Titolo = FilmInserisci.getText();
        Ora = DurataOreFilmAggiungi.getSelectedIndex();
        Ora++;
        System.out.print(Ora);
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_AggiungiFilmButtonActionPerformed

    private void comboEliminaFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEliminaFilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEliminaFilmActionPerformed

    private void DurataOreFilmAggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DurataOreFilmAggiungiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DurataOreFilmAggiungiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel. */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Crea l'oggetto Amministratore qui o ottienilo da un'altra parte
                Amministratore admin = new Amministratore("accesso diretto alla gui","accesso diretto alla gui", Ruolo.UTENTE);
                new GUIadmin(admin).setVisible(true); // Passa l'oggetto al costruttore di GUIadmin
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AggiungiButtonFilm;
    private javax.swing.JButton AggiungiFilmButton;
    private javax.swing.JButton AggiungiSalaButton;
    private javax.swing.JButton ButtonEliminaSala;
    private javax.swing.JButton ButtonModificaSala;
    private javax.swing.JComboBox<String> DurataOreFilmAggiungi;
    private javax.swing.JButton EliminaButtonFilm;
    private javax.swing.JButton EliminaSpettacolo;
    private javax.swing.JTextField FilmInserisci;
    private javax.swing.JComboBox<String> FilmModifica;
    private javax.swing.JLabel FilmTitoloAggiungi;
    private javax.swing.JLabel GestoreFilmTitolo;
    private javax.swing.JTextField InserisciNomeSala;
    private javax.swing.JTextField InserisciNuovaSala;
    private javax.swing.JTextField IserisciOrario;
    private javax.swing.JTextField ModificaOrario;
    private javax.swing.JButton ModificaSpettacoloButton;
    private javax.swing.JLabel OrarioModificaTitolo;
    private javax.swing.JSpinner PostiInserisci;
    private javax.swing.JComboBox<String> SalaModifica;
    private javax.swing.JScrollPane ScrollTabella;
    private javax.swing.JComboBox<String> SelezionaFilmAggiungi;
    private javax.swing.JComboBox<String> SelezionaSala;
    private javax.swing.JComboBox<String> SelezionaSalaElimina;
    private javax.swing.JLabel TitoloCreaSpettacolo;
    private javax.swing.JLabel TitoloEliminaFIlm;
    private javax.swing.JLabel TitoloFilm;
    private javax.swing.JLabel TitoloFilmInserisci;
    private javax.swing.JLabel TitoloGestoreSale;
    private javax.swing.JLabel TitoloModificaEliminaSala;
    private javax.swing.JLabel TitoloNomeSala;
    private javax.swing.JLabel TitoloNuovaSala;
    private javax.swing.JLabel TitoloPostiInserisci;
    private javax.swing.JLabel TitoloSalaModifica;
    private javax.swing.JLabel TitoloSelezionaOrario;
    private javax.swing.JLabel TitoloSelezionaSala;
    private javax.swing.JLabel TitoloSpettacoli;
    private javax.swing.JLabel Titolodurata;
    private javax.swing.JComboBox<String> comboEliminaFilm;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable tabellaSpettacoli;
    private javax.swing.JLabel titoloPostiModifica;
    // End of variables declaration//GEN-END:variables
}
